weather:
   url: http://api.weatherapi.com/v1/current.json
   key: 162709ae4bc541fca51220712221407
   q: "{lat},{long}"
   field_temp_c: "temp_c" 
   field_temp_f: "temp_f"
   field_humidity: "humidity"
   field_wind_speed: "wind_kph"
   ttl: 60  # seconds
sensor:
    temp_hum_sensor: 
        name: "shtc1"
        sys_folder: "/sys/bus/i2c/devices/i2c-1/new_device"
        sensor_identification: "shtc1 0x70"